name: Playwright Tests
on:
  push:
    branches: [ main, master, LoopTechnicalEvaluation ]
  pull_request:
    branches: [ main, master, LoopTechnicalEvaluation ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test || true  # Prevents CI from failing immediately if tests fail

      - name: Ensure Report Exists
        run: mkdir -p playwright-report  # Ensures the directory exists even if tests fail

      - name: Upload Playwright Report
        if: always()  # Ensures report is uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
